### ISSUE TITLE
Error: pathToFileURL is not a function

### ISSUE THREAD

**Issue by berkayakin** [javiertury/babel-plugin-transform-import-meta#7]
Hello. I get the following error when I use your plugin:

`TypeError: url__WEBPACK_IMPORTED_MODULE_0__.pathToFileURL is not a function`

**Comment by javiertury** [comment]
Hi @berkayakin 

Sorry for missing your issue. I guess that you are using this plugin with a browser bundler, but this plugin is intended only for nodejs environments. Web environments are a whole different beast because web bundlers aggregate files into chunks and each bundler loads modules in a different way. In that case, `import.meta.url` should be provided by the web bunder, [see how webpack does it](https://webpack.js.org/api/module-variables/#importmetaurl)
